### ISSUE TITLE
Media query object spread and comma separation have different outcomes  

### ISSUE THREAD

**Issue by aegatlin** [typestyle/typestyle#348] opened 2019-11-02 01:33 UTC
I don't know if this is "expected behavior" or not, but it was very unexpected for me.

I have the following constants:

```typescript
const max = 500
const mobile = { maxWidth: max }
const notMobile = { minWidth: max + 1 }
```

In my codebase the following `style` did **not** pick up the `notMobile` media query:

```typescript
const tableWrapper = style({
  ...media(notMobile, {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center'
  }),
  ...media(mobile, {
    overflowX: 'scroll'
  })
})
```

Changing the code to the following **solved** the problem:

```typescript
const tableWrapper = style(
  media(notMobile, {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center'
  }),
  media(mobile, {
    overflowX: 'scroll'
  })
)
```

I am aware of the [advanced usage section on media queries](https://typestyle.github.io/#/core/concept-media-queries). I am aware that the "recommended" way is the last way I wrote it. However, I think that both approaches are considered "okay" by typescript. In fact, I use both styles interchangeably across multiple projects successfully, until now. If they are not both "okay" then at least it should be mentioned in the docs somewhere (and sorry if it is and I missed it). Otherwise, it is perhaps a bug?

PS I love this library. Keep up the great work :D

**Comment by notoriousb1t** [comment] 2020-03-14 21:36
This is perhaps very late (this ticket has been open for months), but the reason the first example does not show the mobile queries is due to how the spread operator works in JavaScript. Each media() function outputs an object with `{ $nest: ... }`, so the second media() function's `$nest` property overwrites the first.  This isn't a bug, so much as a nuance of JavaScript.

The `...media()` form is okay when you have other `$nest` property, explicit or from a helper. That is why it is recommended that `...` not be used for the helpers. Internally, `style()` merges all of those automatically.

Closing this as WAI (working as intended). Sorry for the late reply. Open source is generally volunteer, so sometimes there isn't someone with time to answer questions quickly.

**Closed by notoriousb1t** 2020-03-14 21:36 UTC
Labels: question
