### ISSUE TITLE
Style definitions with display property only are not working.

### ISSUE THREAD

**Issue by jakubfalenczyk** [typestyle/typestyle#253] opened 2018-04-18 15:04 UTC
I've encountered a recurring issue that every style definition I write that includes only a `display` property ends up not added to `<style>` tag at all.

Sample style definition: 
```
const hidden = style({
  $debugName: "hidden",
  display: "none",
})
```
Doesn't matter if I use `debugName` or not.
If I add any other property to definition the styles are processed fine. 

This works:
```
const hidden = style({
  $debugName: "hidden",
  display: "none",
  position: "inherit",
})
```

**Comment by raurfang** [comment] 2018-05-10 17:32
We tracked this to a problem with non-IE/Edge browsers ignoring styles which have `::-ms-clear` in the selector.
Here is a minimal reproduction: https://codepen.io/lwisniewski/pen/zjWWoe
Typestyle only surfaced this problem because of the style deduplication:
```js
const style1 = style({ display: 'none' })
const style2 = style({
  $nest: {
    "&::-ms-clear": {
      display: "none",
    }
})
```
which results in:
```css
.abc, .def::-ms-clear {
  display: none;
}
```
and this style is not parsed in FF & Chrome.

**Comment by notoriousb1t** [comment] 2018-05-10 18:31
If you add $unique, that will ensure that the nested statement gets its own body:

```ts
const style2 = style({
  $nest: {
    "&::-ms-clear": {
      $unique: true,
      display: "none",
    }
})
```

**Comment by raurfang** [comment] 2018-05-10 19:32
Great advice, thanks!
I guess we can close this issue.

**Closed** 2018-05-10 19:45 UTC
Labels: question
