### ISSUE TITLE
style() function hangs browser (typestyle 1.4)

### ISSUE THREAD

**Issue by mattiLeBlanc** [typestyle/typestyle#192] opened 2017-09-29 06:42 UTC
Hi,

I just upgraded from Typestyle 1.3.3 to 1.4.1 and I noticed my project (angular 4) became unresponsive.

I created a function that returns a flex definition:
```
export const flex = ( flexSize?: number ): string => {

  if ( !flexSize ) {
    return style( {
      '-webkit-flex': 1,
      '-webkit-box-flex': 1,
      flex: 1,
      boxSizing: 'border-box',
    } );
  } else {
    return style( {
      '-webkit-flex': `1 1 ${ flexSize }%`,
      '-ms-flex': `1 1 ${ flexSize }%`,
      '-webkit-box-flex': flexSize,
      flex: `1 1 ${ flexSize }%`,
      maxWidth: `${ flexSize }%`,
      maxHeight: '100%',
      boxSizing: 'border-box',
    } );
  }
};
```
However, returning the `style` function with the flex definition hangs my browser in version 1.4.1.
It looks like an infinite loop.

In my component I just import the flex function and bind it as a private variable so that can access this in my template.

Did anything change that causes this? Or am I abusing the function?

**Comment by notoriousb1t** [comment] 2017-09-29 14:42
Does the flex function get called recursively?  

I tried out your function in the playground and it works, so I don't believe the issue is with TypeStyle itself.  The classNames are deterministic, so given the same input, it should return the same output.

Having worked with Angular 4, I can imagine that it might have to evaluate the entire view when the model changes if an expression is used in a binding.  For instance  ```<div [ngClass]="flex(50)"><?div>```

Given your use case, I think it might be more appropriate and more convenient to make a directive for flex rather than importing into each component as a property.

**Comment by mattiLeBlanc** [comment] 2017-09-30 06:24
I would call it in the template (pug) like this
```
.title-component(class="{{styles.titleComponent}}")
  .container(class="{{flex.combine(flex.layoutColumn, flex.layoutFill )}}")
    h1(highlight) {{ title }} {{subtitle}}
    .foo-area(*ngIf="user" class="{{flex.combine( flex.layoutColumn, flex.centerCenter, flex.flex() )}}")
      div(class="") Welcome, {{user}}
    .bar-area(class="{{flex.combine( flex.layoutRow, flex.spaceAroundCenter )}}")
      div(class="{{flex.flex(1)}}") 1
      div(class="{{flex.flex(19)}}") 2
      div(class="{{flex.flex(80)}}") 3
```
In my controller I just import the the flex functions:
```
import { Component, Input } from '@angular/core';
import { style, classes } from 'typestyle';
import * as flex from './../../styles/flex';
import template from './title.pug';
import { styleDef } from './title.style';


@Component( {
  selector: 'app-title',
  template: template(),
} )

export class TitleComponent {
  styles = styleDef;
  flex = flex;



  constructor(  ) { }
}


```
It worked fine in version 1.3.3. So something changed in version 1.4

**Comment by mattiLeBlanc** [comment] 2017-09-30 06:37
I found the issue:
In version 1.4 using template literals within the Style function is causing an issue:
```
export const flex = ( flexSize: number = 100 ): string => {
  return style( {
    color: 'green',
    boxSizing: 'border-box',
    maxHeight: '100%',
    maxWidth: `${ flexSize }%`,
  } );
```
The maxWidth will hang my browser, but when I get rid of the literal it is rendering the rest of the styles fine.

**Comment by mattiLeBlanc** [comment] 2017-09-30 06:46
I do notice when I just return a string value and console log the style definition, I see it is running quiet a lot
```
{color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "100%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "1%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "19%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "80%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "80%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "100%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "1%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "19%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "80%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "100%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "1%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "19%"}
flex.ts:121 {color: "green", boxSizing: "border-box", maxHeight: "100%", maxWidth: "80%"}
```
I don't know why angular would call it so many times.

**Comment by mattiLeBlanc** [comment] 2017-09-30 10:19
I created a directive which is not causing any issues:
```
import { Directive, ElementRef, Input, Renderer2, HostBinding, OnInit } from '@angular/core';
import { extend, style, classes } from 'typestyle';
import { NestedCSSProperties } from 'typestyle/lib/types';

@Directive(
  {
    selector: '[flex]',
  },
)
export class FlexDirective implements OnInit {

  @Input( 'flex' ) flex: string;

  constructor(
    private el: ElementRef,
    private renderer: Renderer2,
  ) { }

  ngOnInit(): void {

    let flexDefinition: NestedCSSProperties = {
      '-webkit-flex': `1 1 ${ this.flex }%`,
      '-ms-flex': `1 1 ${ this.flex }%`,
      '-webkit-box-flex': this.flex,
      flex: `1 1 ${ this.flex }%`,
      maxWidth: `${ this.flex }%`,
      maxHeight: '100%',
      boxSizing: 'border-box',
    };
    let className = style( flexDefinition );
    this.renderer.addClass( this.el.nativeElement, className );
  }
}

```

However, I am not sure if it is relevant to have a look at the reported issue, since it was introduced in version 1.4

**Comment by notoriousb1t** [comment] 2017-09-30 11:40
I doubt there is an issue with the style() function because it only produces a string. While style() is not side effect-free, the output is deterministic and can be compared by value.

The reason angular is calling the function so many times is because it doesn't know if the output of flex() will change with the model or not.  This is an unfortunate reality with calling functions inside of an angular view.

Please post your package.json.

**Comment by mattiLeBlanc** [comment] 2017-09-30 12:09
```
{
  "name": "angular-starter",
  "version": "1.0.0",
  "description": "Angular 4 starter kit with pug and typestyle",
  "main": "index.js",
  "dependencies": {
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.2.2",
    "@uirouter/angular": "^1.0.0-beta.6",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.0",
    "typestyle": "^1.4.1",
    "zone.js": "^0.8.11"
  },
  "devDependencies": {
    "browser-sync": "^2.18.12",
    "browser-sync-spa": "^1.0.3",
    "del": "^2.2.2",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-filter": "^5.0.0",
    "gulp-hub": "github:frankwallis/gulp-hub#d461b9c700df9010d0a8694e4af1fb96d9f38bf4",
    "gulp-rename": "^1.2.2",
    "gulp-util": "^3.0.8",
    "html-loader": "^0.4.5",
    "html-webpack-plugin": "^2.28.0",
    "path": "^0.12.7",
    "pug": "^2.0.0-rc.2",
    "pug-loader": "^2.3.0",
    "ts-loader": "^2.1.0",
    "tslint": "^5.4.3",
    "tslint-loader": "^3.5.3",
    "typescript": "^2.3.4",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-fail-plugin": "^1.0.6"
  },
  "scripts": {
    "build": "gulp",
    "serve": "gulp serve",
    "serve:dist": "gulp serve:dist",
    "test": "gulp test",
    "test:auto": "gulp test:auto"
  },
  "author": "MSP",
  "license": "ISC"
}

```

**Comment by basarat** [comment] 2017-10-03 05:58
There is a loop in your code (not typestyle, not angular). Closing for now :rose:

# Just to be more helpful

Replace 

```
export const flex = ( flexSize?: number ): string => {

  if ( !flexSize ) {
    return style( {
      '-webkit-flex': 1,
      '-webkit-box-flex': 1,
      flex: 1,
      boxSizing: 'border-box',
    } );
  } else {
    return style( {
      '-webkit-flex': `1 1 ${ flexSize }%`,
      '-ms-flex': `1 1 ${ flexSize }%`,
      '-webkit-box-flex': flexSize,
      flex: `1 1 ${ flexSize }%`,
      maxWidth: `${ flexSize }%`,
      maxHeight: '100%',
      boxSizing: 'border-box',
    } );
  }
};
```
with something simple like 

```js
export const flex = ( flexSize?: number ): string => {

  if ( !flexSize ) {
    return 'foo'
  } else {
    return 'bar'
  }
};
```

And watch it fail. Then fix it :heart:

**Closed by basarat** 2017-10-03 05:58 UTC

**Comment by mattiLeBlanc** [comment] 2017-10-03 06:03
@basarat I don't see the loop in my code. It's a function that returns a style() call based on flexSize being provided.
I do know something does loop since it hangs the browser, but as I pointed out, this code was working in Typestyle 1.3.3 and not in 1.4.1. 

I did move towards a directive to deal with this, no issues there.
And then I found angular-layout which is probably even better.

So if you guys are sure there is nothing wrong in the Typestyle source, I am happy to leave this closed.
It was just that it became an issue when I upgraded your package.

**Comment by basarat** [comment] 2017-10-03 08:39
> I do know something does loop since it hangs the browser, but as I pointed out, this code was working in Typestyle 1.3.3 and not in 1.4.1.

There is no code change between those versions : https://github.com/typestyle/typestyle/compare/v1.3.3...v1.4.1 

Hence we cannot be the cause of this. Sorry that you are having this issue but nothing we would be able to do about it :rose:

**Comment by mattiLeBlanc** [comment] 2017-10-03 10:09
No problem.

I moved to a directive anyway and to the angular-layout package.
